/*CREATE A DATABASE*/
CREATE DATABASE Music;

/*USE THE DATABASE*/
USE Music;

/*CREATE THE TABLES*/
CREATE TABLE USERS(
UserID INT NOT NULL PRIMARY KEY,
EmailID VARCHAR(100) NOT NULL,
LastName VARCHAR(100) NOT NULL,
FirstName VARCHAR(100) NOT NULL,
Age INT NOT NULL,
Country VARCHAR(100) NOT NULL
);

CREATE TABLE PLAYLISTS(
PlaylistID INT NOT NULL PRIMARY KEY,
PlaylistName VARCHAR(100) NOT NULL,
Quantity INT NOT NULL,
PlaylistDescription VARCHAR(100) DEFAULT 'NULL',
UserID INT FOREIGN KEY REFERENCES USERS(UserID)
);

CREATE TABLE ARTISTS(
ArtistID INT NOT NULL PRIMARY KEY,
LastName VARCHAR(100) NOT NULL,
FirstName VARCHAR(100),
Age INT NOT NULL,
Country VARCHAR(100)
);

CREATE TABLE ALBUMS(
AlbumID INT NOT NULL PRIMARY KEY,
AlbumName VARCHAR(100) NOT NULL,
Release DATE,
AlbumDescription VARCHAR(200) DEFAULT 'NULL',
ArtistID INT FOREIGN KEY REFERENCES ARTISTS(ArtistID)
);

CREATE TABLE TRACKS(
TrackID INT NOT NULL PRIMARY KEY,
Title VARCHAR(100) NOT NULL,
Genre VARCHAR(100),
TrackDescription VARCHAR(100) DEFAULT 'NULL',
Ratings decimal(2,1)
CONSTRAINT chk_Ratings CHECK (Ratings >= 0 AND Ratings <= 5),
AlbumID INT FOREIGN KEY REFERENCES ALBUMS(AlbumID)
);

CREATE TABLE PLAYLIST_TRACK(
PlaylistID INT NOT NULL FOREIGN KEY REFERENCES PLAYLISTS(PlaylistID),
TrackID INT NOT NULL FOREIGN KEY REFERENCES TRACKS(TrackID),
CONSTRAINT PK_PLAYLIST_TRACK PRIMARY KEY (PlaylistID,TrackID)
);

/* UNIQUE CONSTRAINT FOR COLUMN EmailID*/
ALTER TABLE USERS ADD UNIQUE(EmailID);




